automatic_scaling:
  max_instances: 2
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8
  max_concurrent_requests: 40
  max_pending_latency: 3000ms
  min_pending_latency: 500ms

env: standard
instance_class: F1
runtime: nodejs16
service: beta

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|webp))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt|webp)$
    secure: always
    http_headers:
      cache-control: public, max-age=31536000 # 1年

  - url: /.*
    secure: always
    script: auto
