default_expiration: 30m
instance_class: F1
runtime: nodejs16

handlers:
  - url: /_nuxt
    static_dir: .output/public/_nuxt
    secure: always
    redirect_http_response_code: 301
    require_matching_file: true
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
      X-Content-Type-Options: nosniff

  - url: /(.*\.(gif|png|jpg|ico|txt|webp|js))$
    static_files: .output/public/\1
    upload: .output/public/.*\.(gif|png|jpg|ico|txt|webp|js)$
    secure: always
    redirect_http_response_code: 301
    require_matching_file: true
    expiration: 365d
    http_headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
      X-Content-Type-Options: nosniff

  - url: /opendata/api/raw/
    static_dir: .output/public/opendata/api/raw/
    secure: always
    redirect_http_response_code: 301
    require_matching_file: true
    http_headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Methods: GET, POST, OPTIONS
      Access-Control-Allow-Headers: Accept, Content-Type, Content-Length, Accept-Encoding
      Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
      X-Content-Type-Options: nosniff

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    require_matching_file: true
    script: auto

automatic_scaling:
  max_instances: 3
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8
  max_concurrent_requests: 40
  max_pending_latency: 3000ms
  min_pending_latency: 500ms
