automatic_scaling:
  max_instances: 2
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8
  max_concurrent_requests: 40
  max_pending_latency: 3000ms
  min_pending_latency: 500ms

env: standard
instance_class: F2
runtime: nodejs16

handlers:
  - url: /_nuxt
    static_dir: .output/public/_nuxt
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|webp))$
    static_files: .output/public/\1
    upload: .output/public/.*\.(gif|png|jpg|ico|txt|webp)$
    secure: always
    expiration: 365d

  - url: /opendata/api/raw/
    static_dir: .output/public/opendata/api/raw/
    secure: always
    http_headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Methods: GET, POST, OPTIONS
      Access-Control-Allow-Headers: Accept, Content-Type, Content-Length, Accept-Encoding

  - url: /.*
    secure: always
    script: auto
