steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      [
        '-c',
        "gcloud app versions list --service=default | grep 0.00 | sort -rk 4,4 | awk '{print $2}' | tail -n +11 | xargs -l gcloud app versions delete {}",
      ]
  - name: ubuntu
    args: ['bash', './workflow_tools/builder/generate_env.sh']
    env:
      - 'GITHUB_CLI_ID=$_GITHUB_CLI_ID'
      - 'GITHUB_CLI_SEC=$_GITHUB_CLI_SEC'
  - name: node:16
    entrypoint: yarn
    args: ['install']
  - name: node:16
    entrypoint: yarn
    args: ['build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']
    timeout: '1600s'
