name: covid19_ibaraki Data Update

on: workflow_dispatch

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: main
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8
      - name: Download Files
        run: |
          curl ${DATA_UPDATE_URL}?data=patients_data -L -o 080004_ibaraki_covid19_patients.csv
          curl ${DATA_UPDATE_URL}?data=tested_people -L -o 080004_ibaraki_covid19_test_people.csv
          curl ${DATA_UPDATE_URL}?data=mutant_tested_people -L -o 080004_ibaraki_covid19_mutant_test_people.csv
          curl ${DATA_UPDATE_URL}?data=call_center -L -o 080004_ibaraki_covid19_call_center.csv
          curl ${DATA_UPDATE_URL}?data=positive_number -L -o 080004_ibaraki_covid19_positive_number.csv
          curl ${DATA_UPDATE_URL}?data=mutant_positive_number -L -o 080004_ibaraki_covid19_mutant_positive_number.json
          curl ${DATA_UPDATE_URL}?data=recovered_number -L -o 080004_ibaraki_covid19_recovered_number.csv
          curl ${DATA_UPDATE_URL}?data=death_number -L -o 080004_ibaraki_covid19_death_number.csv
          curl ${DATA_UPDATE_URL}?data=death_attributes -L -o 080004_ibaraki_covid19_death_attributes.csv
          curl ${DATA_UPDATE_URL}?data=inspections_summary -L -o 080004_ibaraki_covid19_inspections_summary.json
          curl ${DATA_UPDATE_URL}?data=main_summary -L -o 080004_ibaraki_covid19_summary.json
          curl ${DATA_UPDATE_URL}?data=corona_next -L -o 080004_ibaraki_covid19_corona_next.json
          curl ${DATA_UPDATE_URL}?data=forked_sites -L -o otherpref.csv
          curl ${DATA_UPDATE_URL}?data=news_json -L -o news.json
          curl ${DATA_UPDATE_URL}?data=last_update -L -o last_update.json
          curl --compressed https://data.vrs.digital.go.jp/vaccination/opendata/latest/prefecture.ndjson -L -o vaccine_data.ndjson
        working-directory: ./static/opendata/api/raw/covid19_ibaraki/
        env:
          DATA_UPDATE_URL: ${{ secrets.DATA_UPDATE_URL }}
      - name: Convert Vaccine Data
        run: python ../../../../../workflow_tools/opendata/cov19_vaccine_data.py
        working-directory: ./static/opendata/api/raw/covid19_ibaraki
      - name: Remove Base Vaccine Data
        run: rm vaccine_data.ndjson
        working-directory: ./static/opendata/api/raw/covid19_ibaraki
      - name: Create Info Json
        run: python ../../../../../workflow_tools/opendata/covid19_ibk.py
        working-directory: ./static/opendata/api/raw/covid19_ibaraki
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Data" -a
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
