name: i18n Generator

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  i18n-builder:
    if: false == contains(github.event.commits[0].message, 'Update locales/ja.json') || false == contains(github.event.commits[0].message, 'Update COVID-19 Data')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v3.0.2
        with:
          ref: main
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run script
        run: python locales/generator.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update locales/ja.json
          title: Update translation files
          labels: auto_merge
          branch-suffix: 'short-commit-hash'
