name: Pull Request Labeler

on:
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Get actor's name
        run: echo $GITHUB_ACTOR
        env:
          - GITHUB_ACTOR: ${{ github.actor }}
      - name: Label for Transifex
        if: github.actor == 'transifex-integration[bot]' && !endsWith(github.event.pull_request.title, '[manual sync]')
        uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: '.github/labeler/transifex.yml'
      - name: Label for DeepSource
        if: github.actor == 'deepsource-autofix[bot]'
        uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: '.github/labeler/deepsource.yml'
